### ISSUE TITLE
After Update no start

### ISSUE THREAD

**Issue by fugo** [robint99/mate-dock-applet#123]
After update to version 0.81-1 the dock applet don't start.
with CLI some errors and I don't know whats going on.

```
 ths@arch-ant   ~  python /usr/lib/mate-applets/mate-dock-applet/dock_applet.py  1 ↵  305  20:42:36 
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 67, in <module>
    import docked_app
  File "/usr/lib/mate-applets/mate-dock-applet/docked_app.py", line 60, in <module>
    gi.require_version("Bamf", "3")
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Bamf not available
```
Any idea 😞 
I use arch and Mate 1.20.0

**Comment by robint99** [comment]
Try installing the bamf package, that should sort out your problems ☺

**Comment by fugo** [comment]
**thanks a lot!**
don't know that the new version changed that :no_mouth: 
Now it works.
