### ISSUE TITLE
dock doesn't work on linux mint 19 mate

### ISSUE THREAD

**Issue by dylad** [robint99/mate-dock-applet#155]
Hello,
I'm trying to issue dock applet on Linux Mint 19 Mate but it doesn't work at all...
I tried to install the version within bionic repo and the lastest git version, both don't work.

This is the output I get when trying to run dock.py : 
> Traceback (most recent call last):
  File "dock.py", line 82, in <module>
    import dock_win_list
  File "/usr/lib/mate-applets/mate-dock-applet/dock_win_list.py", line 74
SyntaxError: Non-ASCII character '\xe2' in file /usr/lib/mate-applets/mate-dock-applet/dock_win_list.py on line 74, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Any clues ?

**Comment by dylad** [comment]
Ok I was running python instead of python3...
But still, dock appears in the mate panel list but when I try to add it to my panel nothing happens.

**Comment by dylad** [comment]
Manage to solve this issue by reinstalling dock from linux repo and reboot afterwards.
