### ISSUE TITLE
AttributeError in do_window_scroll(): 'NoneType' object has no attribute 'is_running'

### ISSUE THREAD

**Issue by CreamyCookie** [robint99/mate-dock-applet#156]
I think it happens mainly when scrolling on an empty spot on the dock.

```python
 Traceback (most recent call last):
   File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 365, in applet_scroll_event
     the_dock.do_window_scroll(Gdk.ScrollDirection.DOWN, event.time)
   File "/usr/lib/mate-applets/mate-dock-applet/dock.py", line 4173, in do_window_scroll
     if app.is_running() is False:
 AttributeError: 'NoneType' object has no attribute 'is_running'
```

**Comment by robint99** [comment]
I've just committed a fix for this. Thanks for the info!
