### ISSUE TITLE
Crash with ValueError when enabling the option to change the panel color

### ISSUE THREAD

**Issue by oz123** [robint99/mate-dock-applet#65]
full error:
```
 $ python /usr/lib64/mate-applets/mate-dock-applet/dock_applet.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/mate-applets/mate-dock-applet/dock_color_changer.py", line 168, in change_panel_colors
    self.get_dom_color()
  File "/usr/lib64/mate-applets/mate-dock-applet/dock_color_changer.py", line 155, in get_dom_color
    colstr = dom_color.get_dom_color(self.__pf)
  File "/usr/lib64/mate-applets/mate-dock-applet/dom_color.py", line 22, in get_dom_color
    pixels = image.getdata(band=channel)
  File "/usr/lib64/python3.4/site-packages/PIL/Image.py", line 1141, in getdata
    return self.im.getband(band)
ValueError: band index out of range
```

**Comment by robint99** [comment]
Could you send me or link to the background image you're using?

Thanks.

**Comment by oz123** [comment]
I am using the default background of mate 
![screenshot at 2016-07-25 10-53-14](https://cloud.githubusercontent.com/assets/1083045/17095660/05157d6e-5256-11e6-8a2e-14222e516279.png)

**Comment by oz123** [comment]
I just found out the changing the desktop background does change the panel color, but it's not completely free of glitches. Here is another way to produce funny results with another mate wallpaper:
![another glitch](https://cloud.githubusercontent.com/assets/1083045/17132222/10704934-5321-11e6-946c-86d9bb0c0bbb.png)

**Comment by robint99** [comment]
It seems that some backgrounds - particularly the default MATE backgrounds - cause problems. I've pushed a minor fix which simply sets the panel colour to black when this happens...

Cheers,
