### ISSUE TITLE
Dock do not starts. GTK problem?

### ISSUE THREAD

**Issue by nelson6e65** [robint99/mate-dock-applet#72]
Hi again. I'm unable to install, again (#18). :sweat_smile:

![pantallazo-2016-08-21 21-51-27](https://cloud.githubusercontent.com/assets/9272498/17841737/b0fa97d8-67e9-11e6-8803-35a8a6540c0f.png)

Is installed fine, but I don't see the dock in my panel. I got this error when runing 
**`python3 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py `**

**GTK3** `./configure** --prefix=/usr --with-gtk3`

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 138, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python3.5/site-packages/gi/module.py", line 275, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python3.5/site-packages/gi/module.py", line 122, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 54, in <module>
    from gi.repository import MatePanelApplet
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 140, in load_module
    raise ImportError(e)
ImportError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded
```

**GTK2** `./configure --prefix=/usr`

```
/usr/lib/python3.5/site-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dom_color.py", line 11, in <module>
    import Image, ImageDraw
ImportError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/mate-applets/mate-dock-applet/dock_applet.py", line 63, in <module>
    import dock
  File "/usr/lib/mate-applets/mate-dock-applet/dock.py", line 75, in <module>
    import dock_color_changer
  File "/usr/lib/mate-applets/mate-dock-applet/dock_color_changer.py", line 48, in <module>
    import dom_color
  File "/usr/lib/mate-applets/mate-dock-applet/dom_color.py", line 13, in <module>
    from PIL import Image, ImageDraw
ImportError: No module named 'PIL'

```

**Comment by robint99** [comment]
The Gtk version of the applet which you use should match the Gtk version of MATE, so you should only be compiling the Gtk3 applet if you have MATE Gtk3. If you try running the Gtk3 applet on Gtk2 MATE you will have problems....

To solve the ImportError, you need to install the python imaging library. Its normally called something like python-pil or python-pillow, and using dnf or yum extender you should be able to find it easily enough. You need to install the python 3 version.

Hope this gets you up and running :)

**Comment by nelson6e65** [comment]
Hi, @robint99. By installing `python3-pillow` and rebuild the dock using `./configure --prefix=/usr` solved it! Thanks!

```
sudo dnf install python3-pillow
```
